force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>Used on USA Contact Layouts, this field shows the Contact Type from a high level at an Account.</description>
    <inlineHelpText>Please select a Contact Type.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Contractor - Hispanic Outreach</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Homeowner</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Owner/End User</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows a Contact to identify if they&apos;d want to &apos;opt out&apos; of any mailings other then those that do business with Certainteed Gypsum moving forward.</description>
    <inlineHelpText>Check this box if your Contact has stated that they only wish to receive email as it relates to doing business, and not marketing or promotional emails.</inlineHelpText>
    <label>Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Set contact status to active or inactive.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sent_Date__c</fullName>
    <description>This field is used for Gypsum NPS surveys to accommodate sending out list email from Contact list views to a percentage of Contact records.</description>
    <inlineHelpText>The date an email with a Gypsum NPS survey was sent to the Contact.</inlineHelpText>
    <label>Survey Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Gypsum_USA_Contact.recordType-meta.xml
<RecordType>
    <fullName>Gypsum_USA_Contact</fullName>
    <active>true</active>
    <label>Gypsum USA Contact</label>
</RecordType>

force-app/main/default/classes/NPSemailSentScheduler_Test.cls
@istest
class NPSemailSentScheduler_Test {
        @isTest(SeeAllData = false)
    static void test() {
        User userRecord = initTestUser('Testing1');
        System.runAs(userRecord){
            List<RecordType> accountRecord1 = [SELECT Id, Name, DeveloperName FROM RecordType where sobjectType = 'account' AND NAME = 'Ship-To' limit 1];
            List<RecordType > recordTypes = [SELECT Id, Name, DeveloperName FROM RecordType where sobjectType = 'contact' and DeveloperName ='Gypsum_USA_Contact' limit 1];
            
            
            Account ac = new Account();
            Id devRecordTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Payer').getRecordTypeId();
            ac.RecordTypeId = accountRecord1[0].id;
            ac.Name = 'TestAccount';
            ac.BillingCountry = 'USA';
            ac.BillingState = 'TX';
            ac.Shipping_Condition_Desc__c = 'TestAccountRAIL';
            insert ac;
            
            Contact cont = new Contact();
            cont.Survey_Email_Sent__c = true;
            Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Gypsum USA Contact').getRecordTypeId();
            cont.RecordTypeId = recordTypes[0].id;

            cont.FirstName='fname';
            cont.LastName = 'lname';
            cont.Email = 'email@gmail.com';
            cont.Email_Opt_Out__c = false;
            cont.Phone = '9743800309';
            cont.MailingStreet = 'ABC'; 
            cont.MailingCity  = 'ABC';
            cont.MailingState = 'ABC';
            cont.MailingPostalCode = '350250';
            cont.Status__c = 'Active';
            cont.Contact_Type__c  = 'Dealer';
            cont.Survey_Email_Sent__c  = true;
            cont.accountid = ac.id;
            cont.Survey_Sent_Date__c = date.today() - 90;
            insert cont;
            
            Test.startTest();
                NPSemailSentScheduler nps = new NPSemailSentScheduler();
                String sch = '0 0 23 * * ?';
                system.schedule('Test status Check', sch, nps );
            Test.stopTest();
        }
    }

    private static user initTestUser(String userName){
        Profile userPrf = [select id from profile where name='System Administrator'];
        User userRecord = new User(emailencodingkey     = 'UTF-8',
                                    languagelocalekey   = 'en_US',
                                    localesidkey        = 'en_US',
                                    timezonesidkey      = 'America/Los_Angeles',
                                    alias               = 'Tstr', 
                                    lastname            = userName,
                                    email               = userName + '@testorg.com',
                                    profileid           = userPrf.Id, 
                                    username            = userName + UserInfo.getOrganizationId() + '@testorg.com',
                                    sales_org__c        = '1502');
        Insert userRecord;
        return userRecord;
    }
}