force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>Used on USA Contact Layouts, this field shows the Contact Type from a high level at an Account.</description>
    <inlineHelpText>Please select a Contact Type.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Contractor - Hispanic Outreach</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Homeowner</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Owner/End User</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows a Contact to identify if they&apos;d want to &apos;opt out&apos; of any mailings other then those that do business with Certainteed Gypsum moving forward.</description>
    <inlineHelpText>Check this box if your Contact has stated that they only wish to receive email as it relates to doing business, and not marketing or promotional emails.</inlineHelpText>
    <label>Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Set contact status to active or inactive.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Gypsum_USA_Contact.recordType-meta.xml
<RecordType>
    <fullName>Gypsum_USA_Contact</fullName>
    <active>true</active>
    <label>Gypsum USA Contact</label>
</RecordType>

force-app/main/default/classes/SendMassEmailBatchClassTest.cls
@isTest
public class SendMassEmailBatchClassTest {
    static testmethod void test() {
        List<RecordType> accountRecord1 = [SELECT Id, Name, DeveloperName FROM RecordType where sobjectType = 'account' AND NAME = 'Ship-To' limit 1];
        List<RecordType > recordTypes = [SELECT Id, Name, DeveloperName FROM RecordType where sobjectType = 'contact' and DeveloperName ='Gypsum_USA_Contact' limit 1];
        
        Account accountRecord = new Account();
        accountRecord.Name = 'TestAccount';
        accountRecord.BillingCountry = 'USA';
        accountRecord.BillingState = 'TX';
        accountRecord.Shipping_Condition_Desc__c = 'TestAccountRAIL';
        accountRecord.RecordTypeId = accountRecord1[0].id;
        insert accountRecord;
        
        List<Contact> conList = new List<Contact>();
        List<Id> conListId = new List<Id>();
        for (Integer i=0;i<200;i++) {
            Contact m = new Contact( FirstName='fname',
                                    LastName = 'lname',
                                    Email = 'email@gmail.com',
                                    Email_Opt_Out__c = false,
                                    Phone = '9743800309', 
                                    MailingStreet = 'ABC', 
                                    MailingCity  = 'ABC',
                                    MailingState = 'ABC',
                                    MailingPostalCode = '350250',
                                    Status__c = 'Active',
                                    Contact_Type__c  = 'Dealer',
                                    Survey_Email_Sent__c  = false,
                                    accountid = accountRecord.id,
                                    recordTypeId = recordTypes[0].Id);
            conList.add(m);
        }
        insert conList;
        
        conListId.add(conList[0].id);   
        
        
        Test.startTest();
        SendMassEmailBatchClass c = new SendMassEmailBatchClass(conListId);
        Database.executeBatch(c);
        Test.stopTest();
        
    }
 
}