force-app/main/default/objects/Contact/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <label>Contact Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>Required for CTI/Alcatel Integration</description>
    <inlineHelpText>Required for CTI/Alcatel Integration</inlineHelpText>
    <label>Function</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OM Contact</fullName>
                <default>true</default>
                <label>OM Contact</label>
            </value>
            <value>
                <fullName>Telemar</fullName>
            </value>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Company Communications</fullName>
            </value>
            <value>
                <fullName>Credit Contact</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Locator</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Price Increase Communications</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Principle</fullName>
            </value>
            <value>
                <fullName>Project/Technical/R&amp;D</fullName>
            </value>
            <value>
                <fullName>ProTeam</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Set contact status to active or inactive.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CTI_View_More_Controller.cls
public class CTI_View_More_Controller { 


    public List<Account> accounts {get; private set;}
    public List<Contact> contacts {get; private set;}

    public CTI_View_More_Controller() {
        String callerId = ApexPages.currentPage().getParameters().get('ANI');
        List<List<SObject>> searchList = [FIND :callerId IN PHONE FIELDS RETURNING Account(Id,Name, Phone, Parent.Name, BillingStreet, BillingState, BillingPostalCode, BillingCity, JDE_Hierarchy_Level__c, SAP_ACCOUNT__c where(JDE_Hierarchy_Level__c IN('4-Order For','5-Ship To')AND Status__c= 'Active')),Contact(Id,Name, MailingStreet, MailingState, MailingPostalCode, MailingCity, Account.Name, Phone where(Function__c INCLUDES('OM Contact','Telemar')AND Contact_Relationship__c= 'Active'))];
        accounts = ((List<Account>)searchList[0]);
        contacts = ((List<Contact>) searchList[1]);
    }
    

}